apiVersion: v1
kind: Secret
metadata:
  name: carbon-secrets
type: Opaque
data:
  # mongodb+srv://bhoomikachoudary:Bhoomi123@cluster0.l6hdh.mongodb.net/test
  mongodb-uri: bW9uZ29kYitzcnY6Ly9iaG9vbWlrYWNob3VkYXJ5OkJob29taTEyM0BjbHVzdGVyMC5sNmhkaC5tb25nb2RiLm5ldC90ZXN0
  # Bhoomi
  jwt-secret: Qmhvb21p
